### ISSUE TITLE
Attempted to call an undefined method named "id" of class "AppBundle\Entity\User".

### ISSUE THREAD

**Issue by qdequippe** [GetStream/stream-doctrine#1]
Hi,

I am trying to enrich activities but the getter called is by default `id()` ([Enrich.php#L144](https://github.com/GetStream/stream-doctrine/blob/master/src/Enrich.php#L144)) and on my entities it's `getId()`.

Do you think that the best way to handle that is:
1. Use an Interface to get the id? (I can create a PR for this)
2. Make my own Enrich?

Best regards

**Comment by tbarbugli** [comment]
I am not sure how you could solve this by adding an interface, can you share an idea about this? The quick and simple solution in this case would be to add `id` method to your entities and let that return `getId()`

**Comment by qdequippe** [comment]
@tbarbugli yes sure, for example something like

```
interface EnrichedReference {
    public function getId();
}
```

```
class MyEnrichedObject implements EnrichedReference {
    ...
    private $id;
    ...
    public function getId() ...
```

and `$item` here https://github.com/GetStream/stream-doctrine/blob/master/src/Enrich.php#L143 could be a `EnrichedReference`

Maybe my solution is a little bit complex :)
